version: '3'

services: 
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes: 
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        image: nodeapp1
        environment: 
            - APPID=1111
    nodeapp2:
        image: nodeapp2
        environment: 
            - APPID=2222
    nodeapp3:
        image: nodeapp3
        environment: 
            - APPID=3333
    nodeapp4:
        image: nodeapp4
        environment: 
            - APPID=4444